export enum Tab {
    HOME = 'HOME',
    MESSAGES = 'MESSAGES',
    NOTIFICATIONS = 'NOTIFICATIONS',
    ORDER = 'ORDER',
    PACKAGE = 'PACKAGE',
    PROFILE = 'PROFILE',
    SETTINGS = 'SETTINGS',
    TRACKING = 'TRACKING',
}
